### ISSUE TITLE
What's the right way to enable CMake refer external gflags firstly? 

### ISSUE THREAD

**Issue by backyes** [gflags/gflags#180]
Generally, CMAKE_PREFIX_PATH can enable find_library firstly to find external libraries set in CMAKE_PREFIX_PATH. However, it does work for gflags libs.

cmake for gflags is so complicated. 
* why using export cmake in /usr/lib64/cmake/gflags/... ? what's export cmake? 
* what does it mean, GFLAGS_PREFER_EXPORTED_GFLAGS_CMAKE_CONFIGURATION ?
* why find_library(Gflags) will skip CMAKE_PREFIX_PATH setting? does it obey the cmake rules?

**Comment by schuhschuh** [comment]
> why using export cmake in /usr/lib64/cmake/gflags/... ? what's export cmake?

This is common for CMake projects. This is where the build configuration of a package is installed, which is specific to the binary libraries and hence stored in `/usr/lib` rather than `/usr/share`.

See https://cmake.org/cmake/help/v3.7/manual/cmake-packages.7.html#config-file-packages and the other help on this page for details on how `find_package` works in `CONFIG` mode.

> what does it mean, GFLAGS_PREFER_EXPORTED_GFLAGS_CMAKE_CONFIGURATION ?

This option is not part of the gflags library configuration. You must have found it elsewhere, please state where. A Google search reveals a `FindGflags.cmake` module of the Ceres solver that uses it. Please contact the module author if you would like to know more. For this new CMake based gflags library, such `FindGflags.cmake` module is not required. It exists, however, to be able to also find older gflags binary installations which did not include a CMake package configuration file as they were configured using the autotools.

https://ceres-solver.googlesource.com/ceres-solver/+/1.11.0/cmake/FindGflags.cmake

> why find_library(Gflags) will skip CMAKE_PREFIX_PATH setting? does it obey the cmake rules?

`find_package(gflags)` in CONFIG mode looks for a file named `gflags-config.cmake`. This file contains all paths needed to link to the gflags library. There are no `find_library` or `find_path` calls required. Again, you seem to be using a third-party `FindGflags` module. This is not part of this distribution.

https://cmake.org/cmake/help/v3.7/manual/cmake-packages.7.html#using-packages

**Comment by backyes** [comment]
Thanks a lot.

Just setting GFLAGS_PREFER_EXPORTED_GFLAGS_CMAKE_CONFIGURATION=OFF makes all work.

What’s be best way to enable cmake search external libraries and headers firstly?


发件人: Andreas Schuh <notifications@github.com<mailto:notifications@github.com>>
答复: gflags/gflags <reply@reply.github.com<mailto:reply@reply.github.com>>
日期: Tuesday, November 1, 2016 at 5:31 PM
至: gflags/gflags <gflags@noreply.github.com<mailto:gflags@noreply.github.com>>
抄送: baidu baidu <wangyanfei01@baidu.com<mailto:wangyanfei01@baidu.com>>, Author <author@noreply.github.com<mailto:author@noreply.github.com>>
主题: Re: [gflags/gflags] What's the right way to enable CMake refer external gflags firstly? (#180)


why using export cmake in /usr/lib64/cmake/gflags/... ? what's export cmake?

This is common for CMake projects. This is where the build configuration of a package is installed, which is specific to the binary libraries and hence stored in /usr/lib rather than /usr/share.

See https://cmake.org/cmake/help/v3.7/manual/cmake-packages.7.html#config-file-packages and the other help on this page for details on how find_package works in CONFIG mode.

what does it mean, GFLAGS_PREFER_EXPORTED_GFLAGS_CMAKE_CONFIGURATION ?

This option is not part of the gflags library configuration. You must have found it elsewhere, please state where. A Google search reveals a FindGflags.cmake module of the Ceres solver that uses it. Please contact the module author if you would like to know more. For this new CMake based gflags library, such FindGflags.cmake module is not required. It exists, however, to be able to also find older gflags binary installations which did not include a CMake package configuration file as they were configured using the autotools.

https://ceres-solver.googlesource.com/ceres-solver/+/1.11.0/cmake/FindGflags.cmake

why find_library(Gflags) will skip CMAKE_PREFIX_PATH setting? does it obey the cmake rules?

find_package(gflags) in CONFIG mode looks for a file named gflags-config.cmake. This file contains all paths needed to link to the gflags library. There are no find_library or find_path calls required. Again, you seem to be using a third-party FindGflags module. This is not part of this distribution.

https://cmake.org/cmake/help/v3.7/manual/cmake-packages.7.html#using-packages

―

**Comment by schuhschuh** [comment]
> What’s be best way to enable cmake search external libraries and headers firstly?

Check out the documentation of the relevant CMake functions: `find_library`, `find_path`, and `find_package`. These detail exactly the search order and what global variables you may set to influence the search. For example, `CMAKE_LIBRARY_PATH`, `CMAKE_INCLUDE_PATH`, and `CMAKE_PREFIX_PATH`.
