### ISSUE TITLE
Documentation missing from tarball

### ISSUE THREAD

**Issue by doctaweeks** [gflags/gflags#198]
With the move to the documentation being pulled in as a submodule, tag tarballs from GitHub no longer includes documentation. If the submodule was some kind of dependency - another library or project - it would make sense to not be included but the project's own documentation is missing.

I recommend uploading a release tarball that includes a copy of the documentation from the appropriate submodule commit.

**Comment by schuhschuh** [comment]
Thanks for reporting. I would however argue that the documentation is merely for online viewing on GitHub pages at http://gflags.github.io/gflags/. It's only "linked" as submodule
- to not have to switch branches
- to have a reference to the orphan `gh-pages` branch
- to not have copies in `master` and `gh-pages` that need to be kept in sync
- to have a reference to the revision of the docs at a certain release
- for those browsing the repository files online

I see no actual need to include these files in a source release archive, i.e., to have it available offline. There is also no installation rule for these files. They are used for creating a binary release with CPack, however, but I assume the person who wants to run CPack to clone the Git repository (possibly with `--depth=1`) instead of downloading a tar ball.

**Comment by schuhschuh** [comment]
I've just added the link to the online documentation to the README file.

**Comment by doctaweeks** [comment]
There are many environments that do not have unfettered Internet access which make referencing a web page or running git pull challenging or sometimes impossible. Including documentation for offline use is significant in my opinion. It would be good for distribution (since the projects' Github page is the canonical source) to include it in the tarball rather than relying on 3rd parties to essentially repack it.

**Comment by tuxfan** [comment]
Your submodule breaks other projects that use gflags as a submodule. For example, if I try to clone gflags recursively it hangs:

>>>>>> git clone --recursive git@github.com:gflags/gflags.git
Cloning into 'gflags'...
remote: Counting objects: 2143, done.
remote: Total 2143 (delta 0), reused 0 (delta 0), pack-reused 2143
Receiving objects: 100% (2143/2143), 1.43 MiB | 540.00 KiB/s, done.
Resolving deltas: 100% (1236/1236), done.
Checking connectivity... done.
Submodule 'doc' (https://github.com/gflags/gflags.git) registered for path 'doc'
Cloning into 'doc'... (hang)

This is a problem because I would like to include gflags as a submodule of one of my projects, which means that a recursive clone hangs at your documentation. It seems like your submodule introduces a circular dependency by trying to checkout the same repo with the gh-pages branch. It seems kind of hosed...

**Comment by schuhschuh** [comment]
@tuxfan Not "hosed" at all it seems...
```
as12312@cotopaxi:/Users/as12312/Desktop
> git clone --recursive git@github.com:gflags/gflags.git
Cloning into 'gflags'...
remote: Counting objects: 2143, done.
remote: Total 2143 (delta 0), reused 0 (delta 0), pack-reused 2143
Receiving objects: 100% (2143/2143), 1.43 MiB | 968.00 KiB/s, done.
Resolving deltas: 100% (1236/1236), done.
Checking connectivity... done.
Submodule 'doc' (https://github.com/gflags/gflags.git) registered for path 'doc'
Cloning into '/Users/as12312/Desktop/gflags/doc'...
Submodule path 'doc': checked out '971dd2a4fadac9cdab174c523c22df79efd63aa5'

as12312@cotopaxi:/Users/as12312/Desktop
> git --version
git version 2.9.3 (Apple Git-75)
```

**Comment by schuhschuh** [comment]
> There are many environments that do not have unfettered Internet access which make referencing a web page or running git pull challenging or sometimes impossible. Including documentation for offline use is significant in my opinion. It would be good for distribution (since the projects' Github page is the canonical source) to include it in the tarball rather than relying on 3rd parties to essentially repack it.

It's been a while, but IMHO `gflags` is a low-level software library. I cannot imagine any software developer to write code using this library in an environment where they could not have downloaded the `index.html` of the documentation beforehand if they needed it offline (which `git clone` and `git submodule update --init` do). There is no "manual" that comes with this library. The real documentation is the source code as the main stakeholders are C++ developers which should be pretty comfortable reading source code (i.e., the comments in `gflags.h`).
