### ISSUE TITLE
AddressSanitizer with gflags

### ISSUE THREAD

**Issue by m-chaturvedi** [gflags/gflags#214]
ASan seems to complain when we use it on a simple example:
https://gist.github.com/m-chaturvedi/dbb9c6be1f3e5b3ed67f78ae191c9f6a

Output:
https://gist.github.com/m-chaturvedi/aeee657fbc97f34beac5316c55bfbba7

ASAN_OPTIONS=check_initialization_order=1:detect_stack_use_after_return=1:debug=1:verbosity=1

**Comment by schuhschuh** [comment]
I take it this is due to the use of the static mutex variable `global_registry_lock_ ` [here](https://github.com/gflags/gflags/blob/80ebb424a5c1dfe232242b9bb572047318382377/src/gflags.cc#L935). Would you agree?

Given that this global mutex is private and only used in the static `FlagRegistry ::GlobalRegistry()` singleton getter, I would suggest to move the declaration of the static variable into the body of the `FlagRegistry::GlobalRegistry()` right where it is used. Could you try this?

```
FlagRegistry* FlagRegistry::GlobalRegistry() {
  static Mutex lock(Mutex::LINKER_INITIALIZED);
  MutexLock acquire_lock(&lock);
  if (!global_registry_) {
    global_registry_ = new FlagRegistry;
  }
  return global_registry_;
}
```

and remove declaration and definition of `FlagRegistry::global_mutex_lock_`.

**Comment by m-chaturvedi** [comment]
Tried it in the PR, thanks.
