### ISSUE TITLE
reload config file

### ISSUE THREAD

**Issue by eryalee** [gflags/gflags#229]
If gflags had considered reload config file when process is running?

**Comment by schuhschuh** [comment]
Currently, there is a function to reparse flags (including from config files) which will only set flags that were newly registered since the last parsing of the command arguments. It is called [ReparseCommandLineFlags](https://github.com/gflags/gflags/blob/aa2d0f7b4ed11849f40c3a1dc573ac331ebdaebd/src/gflags.h.in#L375).

You could use a [FlagSaver](https://github.com/gflags/gflags/blob/aa2d0f7b4ed11849f40c3a1dc573ac331ebdaebd/src/gflags.h.in#L250) before parsing your command line arguments (or only those relating to the config files) and restore this state before reparsing. I would expect this to then set the flags again with any new values found in the config files.

Example illustrating this approach (may not working as is, i.e., untested):
```
#include <memory>
#include "gflags/gflags.h"

int main(int argc, char *argv[])
{
  std::unique_ptr<gflags::FlagSaver> current_flags(new gflags::FlagSaver());
  gflags:: ParseCommandLineFlags(&argc, &argv, true);
  // ... config files changed ... reload
  current_flags.reset(); // restore
  current_flags.reset(new gflags::FlagSaver()); // save restored flags again
  gflags:: ReparseCommandLineNonHelpFlags(); // reparse new values
  // ... possibly repeat the above any time configs should be reloaded

  return 0;
}
```

Another approach might be to not have the library remove the flags from `argv` and simply call `ParseCommandLineFlags` again:
```
#include "gflags/gflags.h"

int main(int argc, char *argv[])
{
  gflags:: ParseCommandLineFlags(&argc, &argv, false);
  // ... config files changed ... reload
  gflags:: ParseCommandLineFlags(&argc, &argv, false);

  return 0;
}
```

Give it a try and let me (and others that come across this thread) know which one worked.

**Comment by eryalee** [comment]
thanks @schuhschuh , both of them works well.

**Comment by westfly** [comment]
> 

It's thread-safe ?

when I want to reload config by calling api ReadFromFlagsFile which marked  mostly-deprecated, program coredump at random place.
