### ISSUE TITLE
why not use static variable in singleton GlobalRegistry

### ISSUE THREAD

**Issue by dl239** [gflags/gflags#265]
GlobalRegistry use a static lock to make sure new only once. Why not use a static variable in singleton GlobalRegistry like this.
FlagRegistry* GlobalFlagRegistry() {
  static FlagRegistry flag_registry;
  return &flag_registry;
}

**Comment by schuhschuh** [comment]
I believe the motivation is to make the initialization of `global_registry_` thread-safe. Your [Construct On First Use Idiom](https://isocpp.org/wiki/faq/ctors#static-init-order-on-first-use) based solution takes care of the static initialization order issue, but isn't thread-safe. You can read more about this in [this SO thread](https://stackoverflow.com/questions/1005685/c-static-initialization-order).

The use of a pointer instead of a static variable in the function scope may be intended to avoid destruction of this object while it will be accessed again by a destructor of a global object.
