### ISSUE TITLE
GFlags is not working with target application 

### ISSUE THREAD

**Issue by MohammedAtharKhan** [gflags/gflags#300]
We recently migrated our code from VS 2015 to VS 2019. Now we see GFlags is not able to launch target application when we have Page Heap enabled.

**Comment by MohammedAtharKhan** [comment]
Can anyone look into this with high priority

**Comment by schuhschuh** [comment]
I think your issue report is missing a lot of information. At this point, it is not even clear the issue is with the gflags library build configuration or source code. 

Also, are you referring to https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/gflags ? This is not the gflags library, this seems a Microsoft debugging tool you might be referring to instead?
