### ISSUE TITLE
Sequence of flags?

### ISSUE THREAD

**Issue by thestumbler** [gflags/gflags#319]
(1) I'm refactoring some legacy code to use `gflags`, and ran into an issue. In this original program, which used `getopt()`, the sequence of flags had meaning. I don't see any way to determine the sequence with `gflags`, short of manually parsing the command line before invoking `gflags`. 

Is there any way to determine the sequence of given command line flags, or maybe walking through them one at a time?

(2) [EDIT] I just found another issue. Flags which take a parameter appear to require you to type the parameter. Is that correct? This legacy program's logic makes a distinction between the omission of a parameter and its presence. If the flag is present but no value specified, it takes the default value. If the flag is omitted, it means basically _don't do the action associated with this flag_.

Running the program like this:
```bash
$ program 
```
means something different than
```bash
$ program --n
$ program --n=15
```
In the refactored version, consider this flag with a default integer value:
```clang
DEFINE_int32(  n,  0,    "Some integer" );
```
I don't see any way to replicate this original behavior using `gflags`. I can use `GetCommandLineFlagInfoOrDie().is_default` to determine that the flag was omitted from the command line, but there's an error if the user gives the flag without any value
```bash
$ program          # okay
$ program --n=15   # okay
$ program --n      # error
ERROR: flag '-n' is missing its argument; flag description: Some integer
```

-Chris

**Comment by schuhschuh** [comment]
Hi Chris, I don't think either of your two legacy use cases are meant to be possible with gflags.

The first one you may get by with by going through the `argv` list yourself, looking out only for a few known "action" flags or with the following workaround using validators. If actions could be repeated by providing them multiple times, but with different values, you would furthermore have to chunk the argv to have access to these intermediate values that would be otherwise overridden by the last occurrence. While it would be possible to provide information on the order in which flags were set, in general, programs using gflags are not supposed to depend on the order of the options given. Especially considering also flag files or flags set from environment variables. That said, I think you could possibly use flag validators to update your own list (or map from flag name to a global static counter that is incremented each time an action flag was encountered), i.e., something along the lines of:

```c++
std::vector<const char *> actions;

static bool AppendAction(const char* flagname, bool value) {
  actions.push_back(flagname);
  return true;
}

DEFINE_bool(action1, false, "Action 1");
DEFINE_bool(action2, false, "Action 2");

DEFINE_validator(action1, &AppendAction);
DEFINE_validator(action2, &AppendAction);
```

Note, however, that validators are also invoked by [ValidateUnmodifiedFlags](https://github.com/gflags/gflags/blob/827c769e5fc98e0f2a34c47cef953cc6328abced/src/gflags.cc#L1960) in an undefined order.

Optional flag values, on the other hand, could introduce ambiguities in regards to positional arguments. If an argument following such option flag does not start with a dash (or is actually a string value that happens to start with a dash... which then would need escaping), it could be either a value for this flag or a positional argument. One could of course define a preference for flag values as in other libraries (e.g., Python argparse), but the philosophy behind gflags I think is more often than not to avoid any cases that could introduce ambiguity and resulting unintended program call due to user mistake.

**Comment by thestumbler** [comment]
I agree. Case 1 is a little weird, and I would personally try to avoid it in programs I write. I'm on the fence regarding case 2, as it seems to have some uses. But I understand the ambiguity it introduces as you point out. If I wanted to implement case 2, conceptually I would solve the ambiguity by not using positional arguments for that program. For example, an output file would require a flag like `myprog -speed 60 -outfile log.txt` vs `myprog -speed 60 log.txt`. But code-wise, I don't think this is possible at present using `gflags`.

In my immediate situation, I am going to give up trying to shoehorn `gflags` into this legacy code port and use the original `getopts()` approach.  I will reserve using `gflags` for new programs.
